### Site metadata ###

site_name: Geo-Epic
site_description: Python Utility function to run EPIC model
site_url: https://smarsgroup.github.io/geoepic-docs/

repo_url: https://github.com/smarsGroup/geoepic-docs

# site_dir: './site'
### Build settings ###

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name:  bootstrap4
  custom_dir: custom
  suppress_nextprev: false
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  features:
    - content.code.select
    - content.code.annotate

nav:
  - Home: index.md
  - EPIC Model: epic.md
  - User Guide:
    - Crop Sequence Boundaries: csb.md
    - Weather Module: Weather.md
    - Soil Module: Soil.md
    - Crop Management: OPC.md
  - Quick Start:
    - Model Calibration: opt.md
    - Running an Experiment: runepic.md
    - Code in Python: runexp.md
  - API: api.md
